paths:
  input_dir: "./intervention_graph_creation/data/raw/ard_json"
  output_dir: "./intervention_graph_creation/data/processed"

falkordb:
  host: "localhost"
  port: 6379
  graph: "AISafetyIntervention"
